module.exports = exports = [
    // `./common/*.jsx`,
    // `./common/**/*.jsx`,
    // `./common/**/**/*.jsx`,
    // `./common/**/**/**/*.jsx`,
    // `./asia_finance/*.jsx`,
    // `./asia_finance/**/*.jsx`,
    // `./asia_finance/**/**/*.jsx`,
    // `./asia_finance/**/**/**/*.jsx`,
    // `./business_vault/*.jsx`,
    // `./business_vault/**/*.jsx`,
    // `./business_vault/**/**/*.jsx`,
    // `./business_vault/**/**/**/*.jsx`,
    // `./apps/*.jsx`,
    // `./apps/**/*.jsx`,
    // `./apps/**/**/*.jsx`,
    // `./apps/**/**/**/*.jsx`,
    // `./shared/*.jsx`,
    // `./shared/**/*.jsx`,
    // `./shared/**/**/*.jsx`,
    // `./shared/**/**/**/*.jsx`,
]
