const COOKIE_USER = 'af-usr'
const COOKIE_JWT = 'af-jwt'
const OPEN_LOGIN_POPUP= 'OPEN_LOGIN_POPUP'
const LOGIN= 'LOGIN'
const CHANGE_PASSWORD= 'CHANGE_PASSWORD'
const ACTIVATE_ACCOUNT= 'ACTIVATE_ACCOUNT'
const LOGIN_FAIL= 'LOGIN_FAIL'
const LOGOUT= 'LOGOUT'
const RELOAD_USER_DATA= 'RELOAD_USER_DATA'
const SAVE_MAPPING= 'SAVE_MAPPING'
const SIGNUP_SUCCESS= 'SIGNUP_SUCCESS'
const UPDATE_USER_PROFILE_PIC= 'UPDATE_USER_PROFILE_PIC'
const SAVE_PROFILE = 'SAVE_PROFILE'
export {
    COOKIE_USER,
    COOKIE_JWT,
    OPEN_LOGIN_POPUP,
    LOGIN,
    CHANGE_PASSWORD,
    ACTIVATE_ACCOUNT,
    LOGIN_FAIL,
    LOGOUT,
    RELOAD_USER_DATA,
    SAVE_MAPPING,
    SIGNUP_SUCCESS,
    UPDATE_USER_PROFILE_PIC,
    SAVE_PROFILE
}
